### Gradle properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

### Mod Gradle properties
net.minecraftforge.gradle.merge-source-sets=true
fabric.loom.disableObfuscation=true
multiloader.enableAdvancedVersionSearch=true
multiloader.editPublishVersions=true

### Mod properties
mod.name=Incognito Mods
mod.id=incognito_mods
mod.version=1.0
mod.description=Controls the mod list sent to servers via the minecraft:mod_list packet

### Publishing
mod.modrinth=3pslFSgU
mod.curseforge=1708706
mod.github=incognito-mods

26.3.version=26.4-snapshot-1
